volumes:
  postgres_data: {}
  redis_data: {}

services:

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: development_loan_profit_calculator
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: ${RAILS_ENV:-development}
      DATABASE_HOST: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: development_loan_profit_calculator
      DATABASE_PORT: 5432
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:6.0